#!/system/xbin/bash

bootdebi_dir=/system/etc/bootdebi

until [[ $(getprop sys.boot_completed) = 1 ]] && [[ $(getprop dev.bootcomplete) = 1 ]] && [[ $(getprop service.bootanim.exit) = 1 ]] && [[ $(getprop init.svc.bootanim) = stopped ]]; do

    sleep 10

done

sleep 20

$bootdebi_dir/scripts/bootdebi start

exit 0

