#!/system/xbin/bash

if [[ -e /data/dropbear/pdsshd.conf ]]; then 

  . /data/dropbear/pdsshd.conf

else

  mkdir -p /data/dropbear

  chmod 0600 /data/dropbear

  cp /system/etc/pdsshd.conf /data/dropbear/pdsshd.conf

  . /data/dropbear/pdsshd.conf

fi

if [[ ! -e /data/dropbear/pdsshd.conf ]]; then

  . /system/etc/pdsshd.conf

fi

if [ -e $PID ]; then

  kill -9 $(cat $PID)
  rm $PID

fi

if [[ ! $SSH == 1 ]]; then

  exit 0

fi

/system/exbin/dropbear -A -N root -U 0 -G 0 -T /etc/.ssh/authorized_keys/id_rsa.pub -C "$PASS" -p "$PORT" -P $PID -c /system/xbin/bash

echo "Check if Dropbear is running..."

echo ""

ps -A | grep dropbear

echo "" 

echo "done"

exit 0

